# doc: https://docs.github.com/en/actions
# custom: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17

name: 'Get .NET version'
description: 'Fetch .NET version from '
inputs:
  file_path:  
    description: 'Relative file path'
    required: false
    default: 'Directory.Build.props'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=version::$(egrep -o "[0-9]+\.[0-9]+\.[0-9]+" ${{ inputs.file_path}})"
      shell: bash